### ISSUE TITLE
Font on side wikipedia is unreadable 

### ISSUE THREAD

**Issue by avatar-lavventura** [dracula/duckduckgo#1]
As you can see on the picture side wiki's font color is black and unreadable.

<img width="1231" alt="Screen Shot 2020-01-04 at 20 18 26" src="https://user-images.githubusercontent.com/18537398/71769238-6dc7cb00-2f2f-11ea-9fce-1b7edd5cb2b1.png">

**Comment by avatar-lavventura** [comment]
Is there any update in this issue or would it be considered?

**Comment by bigpick** [comment]
Strange, when I navigate to the same page, I see:

![Screen Shot 2021-03-18 at 2 48 23 PM](https://user-images.githubusercontent.com/9803299/111680894-0d9e0b80-87f9-11eb-9077-db2a941d505f.png)

this is after accessing duckduckgo.com from Chrome, enabling the theme, and then searching for this page

**Comment by avatar-lavventura** [comment]
sorry I forget to mention, I am having this issue under `Safari`

**Comment by bigpick** [comment]
Just tried on Safari, I see the same thing as my above screenshot still.

Can you try:
1. Open Safari, go to duckduckgo.com
2. Enable developer menu (Safari -- top left -> Preferences -> Advanced -> Show Develop menu in menu bar)
3. Open javascript console in safari (Develop -> Show Javascript console)
4. Paste in
```js
var dracula=["7=282a36","8=f8f8f2","9=50fa7b","ae=t","t=p","s=m","w=n","m=l","o=s","j=282a36","a=p","aa=bd93f9","u=-1","x=f1fa8c","y=44475a","af=1","ai=1","f=1"];for(var i=0;i<dracula.length;i++)document.cookie=dracula[i];alert('Appearance settings have successfully been updated!');location.reload();
```
5. Say ok on the dialog that it was applied
6. Search for Roger Federer through duckduckgo again?

**Comment by avatar-lavventura** [comment]
@bigpick I have done your guide but still I am having the same issue; fonts under Roger Federer is all black :-(

**Comment by bigpick** [comment]
Hm... And I tried on Safari using both macOS Dark and Light theme, in case that made a difference on my end (it did not).

What Safari version are you using? I have (with Big Sur):

```
Version 14.0.3 (16610.4.3.1.4)
```

**Comment by bigpick** [comment]
Also maybe worth mentioning that may layout looks entirely different than yours... Notice the lack of the "recent news" section, for example. Do you still also see the recent news sections as well?

Do you have any other further duckduckgo configurations/settings other than the default values?

---

edit, actually, now that I think about it, before you tried the above, did you disable the previously enabled Dracula theme? I would probably suggest doing that first, and then retry the above


Alternative is, can you confirm that your https://duckduckgo.com/settings#appearance looks like the following with regard to the color values?:

![Screen Shot 2021-03-22 at 4 25 27 PM](https://user-images.githubusercontent.com/9803299/112053876-486eaf00-8b2b-11eb-8dfd-271df8ad4c7b.png)

**Comment by avatar-lavventura** [comment]
I was using [dark reader](https://darkreader.org) but change it (on/off) did not have any affect. 

I am using `macOS Catalina Version 10.15.7`, couldn't have encourage to switch to Big Sur.

Ah find it!

`Result Hover, Module, and Dropdown Background Color` was set to `#fffff` on my end (not sure why) and setting dracula theme didn't overwrite it. Changing it into `#222222` fixed the problem:

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/18537398/112203636-d0d07b00-8c23-11eb-82ba-54432cd0d3f5.png">

**Comment by bigpick** [comment]
@avatar-lavventura Hey, awesome, glad to hear it's fixed for you!
